In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('synthetic_customer_churn_data.csv')

In [3]:
df

,customer_id,visits_count,unit_price_ave,first_visit_date,last_visit_date,gender,age,distance,menu,unit_price_per_visits_count,churn
0,1,5,3543.80,2012-07-01,2013-06-29,Male,72,3.24,Child Cut,708.76,0
1,2,4,3392.01,2010-07-24,2011-05-08,Male,25,12.49,Child Cut,848.00,0
2,3,4,2542.38,2016-03-03,2017-02-02,Male,12,4.36,School Cut,635.60,1
3,4,5,4416.75,2015-06-30,2015-11-24,Male,12,2.31,Child Cut,883.35,0
4,5,5,2708.92,2015-01-03,2015-02-08,Male,79,0.05,School Cut,541.78,0
...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,3,3117.15,2019-02-20,2019-10-05,Female,60,17.94,Perm,1039.05,0
49996,49997,5,3338.02,2016-02-20,2017-01-02,Male,42,2.69,Perm,667.60,0
49997,49998,5,3592.89,2012-06-06,2012-12-15,Male,0,35.68,Coloring,718.58,0
49998,49999,1,3227.65,2020-10-26,2021-05-18,Male,22,12.13,Perm,3227.65,0
49999,50000,8,1884.21,2013-07-15,2013-12-02,Female,55,0.09,Child Cut,235.53,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  50000 non-null  int64
 1   visits_count                 50000 non-null  int64
 2   unit_price_ave               50000 non-null  float64
 3   first_visit_date             50000 non-null  object
 4   last_visit_date              50000 non-null  object
 5   gender                       50000 non-null  object
 6   age                          50000 non-null  int64
 7   distance                     50000 non-null  float64
 8   menu                         50000 non-null  object
 9   unit_price_per_visits_count  50000 non-null  float64
 10  churn                        50000 non-null  int64
dtypes: float64(3), int64(4), object(4)
memory usage: 4.2+ MB

In [5]:
df['menu'].unique()

array(['Child Cut', 'School Cut', 'Gray Hair Dye', 'Coloring', 'Perm',
       'Haircut'], dtype=object)

In [8]:
df['menu'].value_counts()   ## menu all type is consider same number

menu
Perm             8427
Haircut          8423
Gray Hair Dye    8310
Child Cut        8308
Coloring         8273
School Cut       8259
Name: count, dtype: int64

In [9]:
df['gender'].unique()

array(['Male', 'Unknown', 'Female'], dtype=object)

In [10]:
df['gender'].value_counts()

gender
Male       16821
Female     16649
Unknown    16530
Name: count, dtype: int64

In [11]:
df.shape

(50000, 11)

In [21]:
# Permanently drop rows with 'Unknown' gender
df = df[df['gender'].str.lower() != 'unknown'].reset_index(drop=True)  ## Total 50000-16530=33470 rows

In [22]:
df

,customer_id,visits_count,unit_price_ave,first_visit_date,last_visit_date,gender,age,distance,menu,unit_price_per_visits_count,churn
0,1,5,3543.80,2012-07-01,2013-06-29,Male,72,3.24,Child Cut,708.76,0
1,2,4,3392.01,2010-07-24,2011-05-08,Male,25,12.49,Child Cut,848.00,0
2,3,4,2542.38,2016-03-03,2017-02-02,Male,12,4.36,School Cut,635.60,1
3,4,5,4416.75,2015-06-30,2015-11-24,Male,12,2.31,Child Cut,883.35,0
4,5,5,2708.92,2015-01-03,2015-02-08,Male,79,0.05,School Cut,541.78,0
...,...,...,...,...,...,...,...,...,...,...,...
33465,49996,3,3117.15,2019-02-20,2019-10-05,Female,60,17.94,Perm,1039.05,0
33466,49997,5,3338.02,2016-02-20,2017-01-02,Male,42,2.69,Perm,667.60,0
33467,49998,5,3592.89,2012-06-06,2012-12-15,Male,0,35.68,Coloring,718.58,0
33468,49999,1,3227.65,2020-10-26,2021-05-18,Male,22,12.13,Perm,3227.65,0
33469,50000,8,1884.21,2013-07-15,2013-12-02,Female,55,0.09,Child Cut,235.53,0

In [23]:
df['gender'].value_counts()    ## male and female is consider same number

gender
Male      16821
Female    16649
Name: count, dtype: int64

In [25]:
df.isnull().sum()  ## no missing value

customer_id                    0
visits_count                   0
unit_price_ave                 0
first_visit_date               0
last_visit_date                0
gender                         0
age                            0
distance                       0
menu                           0
unit_price_per_visits_count    0
churn                          0
dtype: int64

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33470 entries, 0 to 33469
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  33470 non-null  int64
 1   visits_count                 33470 non-null  int64
 2   unit_price_ave               33470 non-null  float64
 3   first_visit_date             33470 non-null  object
 4   last_visit_date              33470 non-null  object
 5   gender                       33470 non-null  object
 6   age                          33470 non-null  int64
 7   distance                     33470 non-null  float64
 8   menu                         33470 non-null  object
 9   unit_price_per_visits_count  33470 non-null  float64
 10  churn                        33470 non-null  int64
dtypes: float64(3), int64(4), object(4)
memory usage: 2.8+ MB

## list of column which datatype is object is first_visit_date,last_visit_date,gender,menu

In [29]:
## we use Nominal / One-Hot Encoding (OHE) . 
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [31]:
encoder=OneHotEncoder()
encoded=encoder.fit_transform(df[['menu']]).toarray()

In [39]:
# Get column names for encoded data
encoded_columns = encoder.get_feature_names_out(['menu'])
df_encoded = pd.DataFrame(encoded, columns=encoded_columns)

In [40]:
df_encoded

,menu_Child Cut,menu_Coloring,menu_Gray Hair Dye,menu_Haircut,menu_Perm,menu_School Cut
0,1.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0
3,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...
33465,0.0,0.0,0.0,0.0,1.0,0.0
33466,0.0,0.0,0.0,0.0,1.0,0.0
33467,0.0,1.0,0.0,0.0,0.0,0.0
33468,0.0,0.0,0.0,0.0,1.0,0.0
33469,1.0,0.0,0.0,0.0,0.0,0.0

In [42]:
df = pd.concat([df, df_encoded], axis=1)

In [43]:
df

,customer_id,visits_count,unit_price_ave,first_visit_date,last_visit_date,gender,age,distance,unit_price_per_visits_count,churn,...,menu_Gray Hair Dye,menu_Haircut,menu_Perm,menu_School Cut,menu_Child Cut,menu_Coloring,menu_Gray Hair Dye,menu_Haircut,menu_Perm,menu_School Cut
0,1,5,3543.80,2012-07-01,2013-06-29,Male,72,3.24,708.76,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,2,4,3392.01,2010-07-24,2011-05-08,Male,25,12.49,848.00,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,3,4,2542.38,2016-03-03,2017-02-02,Male,12,4.36,635.60,1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,5,4416.75,2015-06-30,2015-11-24,Male,12,2.31,883.35,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,5,5,2708.92,2015-01-03,2015-02-08,Male,79,0.05,541.78,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33465,49996,3,3117.15,2019-02-20,2019-10-05,Female,60,17.94,1039.05,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
33466,49997,5,3338.02,2016-02-20,2017-01-02,Male,42,2.69,667.60,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
33467,49998,5,3592.89,2012-06-06,2012-12-15,Male,0,35.68,718.58,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
33468,49999,1,3227.65,2020-10-26,2021-05-18,Male,22,12.13,3227.65,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
33469,50000,8,1884.21,2013-07-15,2013-12-02,Female,55,0.09,235.53,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33470 entries, 0 to 33469
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  33470 non-null  int64
 1   visits_count                 33470 non-null  int64
 2   unit_price_ave               33470 non-null  float64
 3   first_visit_date             33470 non-null  object
 4   last_visit_date              33470 non-null  object
 5   gender                       33470 non-null  object
 6   age                          33470 non-null  int64
 7   distance                     33470 non-null  float64
 8   unit_price_per_visits_count  33470 non-null  float64
 9   churn                        33470 non-null  int64
 10  menu_Child Cut               33470 non-null  float64
 11  menu_Coloring                33470 non-null  float64
 12  menu_Gray Hair Dye           33470 non-null  float64
 13  menu_Haircut                 33470 non-null  float64
 14  menu_Perm                    33470 non-null  float64
 15  menu_School Cut              33470 non-null  float64
 16  menu_Child Cut               33470 non-null  float64
 17  menu_Coloring                33470 non-null  float64
 18  menu_Gray Hair Dye           33470 non-null  float64
 19  menu_Haircut                 33470 non-null  float64
 20  menu_Perm                    33470 non-null  float64
 21  menu_School Cut              33470 non-null  float64
dtypes: float64(15), int64(4), object(3)
memory usage: 5.6+ MB

In [45]:
## convert first_visit_date and last_visit_date column to datetime
df['first_visit_date']=pd.to_datetime(df['first_visit_date'])
df['last_visit_date']=pd.to_datetime(df['last_visit_date'])

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33470 entries, 0 to 33469
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  33470 non-null  int64
 1   visits_count                 33470 non-null  int64
 2   unit_price_ave               33470 non-null  float64
 3   first_visit_date             33470 non-null  datetime64[ns]
 4   last_visit_date              33470 non-null  datetime64[ns]
 5   gender                       33470 non-null  object
 6   age                          33470 non-null  int64
 7   distance                     33470 non-null  float64
 8   unit_price_per_visits_count  33470 non-null  float64
 9   churn                        33470 non-null  int64
 10  menu_Child Cut               33470 non-null  float64
 11  menu_Coloring                33470 non-null  float64
 12  menu_Gray Hair Dye           33470 non-null  float64
 13  menu_Haircut                 33470 non-null  float64
 14  menu_Perm                    33470 non-null  float64
 15  menu_School Cut              33470 non-null  float64
 16  menu_Child Cut               33470 non-null  float64
 17  menu_Coloring                33470 non-null  float64
 18  menu_Gray Hair Dye           33470 non-null  float64
 19  menu_Haircut                 33470 non-null  float64
 20  menu_Perm                    33470 non-null  float64
 21  menu_School Cut              33470 non-null  float64
dtypes: datetime64[ns](2), float64(15), int64(4), object(1)
memory usage: 5.6+ MB

In [47]:
## create new feature - days since last visit
df['days_since_last_visit']=(df['last_visit_date'].max()-df['last_visit_date']).dt.days

In [48]:
df

,customer_id,visits_count,unit_price_ave,first_visit_date,last_visit_date,gender,age,distance,unit_price_per_visits_count,churn,...,menu_Haircut,menu_Perm,menu_School Cut,menu_Child Cut,menu_Coloring,menu_Gray Hair Dye,menu_Haircut,menu_Perm,menu_School Cut,days_since_last_visit
0,1,5,3543.80,2012-07-01,2013-06-29,Male,72,3.24,708.76,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3463
1,2,4,3392.01,2010-07-24,2011-05-08,Male,25,12.49,848.00,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4246
2,3,4,2542.38,2016-03-03,2017-02-02,Male,12,4.36,635.60,1,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2149
3,4,5,4416.75,2015-06-30,2015-11-24,Male,12,2.31,883.35,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2585
4,5,5,2708.92,2015-01-03,2015-02-08,Male,79,0.05,541.78,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2874
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33465,49996,3,3117.15,2019-02-20,2019-10-05,Female,60,17.94,1039.05,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1174
33466,49997,5,3338.02,2016-02-20,2017-01-02,Male,42,2.69,667.60,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2180
33467,49998,5,3592.89,2012-06-06,2012-12-15,Male,0,35.68,718.58,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3659
33468,49999,1,3227.65,2020-10-26,2021-05-18,Male,22,12.13,3227.65,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,583
33469,50000,8,1884.21,2013-07-15,2013-12-02,Female,55,0.09,235.53,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3307

In [49]:
## Drop unnecessary columns
df.drop(['customer_id','first_visit_date','last_visit_date'],axis=1,inplace=True)

In [50]:
df

,visits_count,unit_price_ave,gender,age,distance,unit_price_per_visits_count,churn,menu_Child Cut,menu_Coloring,menu_Gray Hair Dye,menu_Haircut,menu_Perm,menu_School Cut,menu_Child Cut,menu_Coloring,menu_Gray Hair Dye,menu_Haircut,menu_Perm,menu_School Cut,days_since_last_visit
0,5,3543.80,Male,72,3.24,708.76,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3463
1,4,3392.01,Male,25,12.49,848.00,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4246
2,4,2542.38,Male,12,4.36,635.60,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2149
3,5,4416.75,Male,12,2.31,883.35,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2585
4,5,2708.92,Male,79,0.05,541.78,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2874
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33465,3,3117.15,Female,60,17.94,1039.05,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1174
33466,5,3338.02,Male,42,2.69,667.60,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2180
33467,5,3592.89,Male,0,35.68,718.58,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3659
33468,1,3227.65,Male,22,12.13,3227.65,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,583
33469,8,1884.21,Female,55,0.09,235.53,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3307

In [51]:
## apply encoding technique in gneder column used LabelEncoder
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['gender'] = encoder.fit_transform(df['gender'])

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33470 entries, 0 to 33469
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   visits_count                 33470 non-null  int64
 1   unit_price_ave               33470 non-null  float64
 2   gender                       33470 non-null  int32
 3   age                          33470 non-null  int64
 4   distance                     33470 non-null  float64
 5   unit_price_per_visits_count  33470 non-null  float64
 6   churn                        33470 non-null  int64
 7   menu_Child Cut               33470 non-null  float64
 8   menu_Coloring                33470 non-null  float64
 9   menu_Gray Hair Dye           33470 non-null  float64
 10  menu_Haircut                 33470 non-null  float64
 11  menu_Perm                    33470 non-null  float64
 12  menu_School Cut              33470 non-null  float64
 13  menu_Child Cut               33470 non-null  float64
 14  menu_Coloring                33470 non-null  float64
 15  menu_Gray Hair Dye           33470 non-null  float64
 16  menu_Haircut                 33470 non-null  float64
 17  menu_Perm                    33470 non-null  float64
 18  menu_School Cut              33470 non-null  float64
 19  days_since_last_visit        33470 non-null  int64
dtypes: float64(15), int32(1), int64(4)
memory usage: 5.0 MB

In [53]:
## split into independent and dependent feature
X=df.drop(columns=['churn'])
y=df['churn']

In [54]:
X

,visits_count,unit_price_ave,gender,age,distance,unit_price_per_visits_count,menu_Child Cut,menu_Coloring,menu_Gray Hair Dye,menu_Haircut,menu_Perm,menu_School Cut,menu_Child Cut,menu_Coloring,menu_Gray Hair Dye,menu_Haircut,menu_Perm,menu_School Cut,days_since_last_visit
0,5,3543.80,1,72,3.24,708.76,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3463
1,4,3392.01,1,25,12.49,848.00,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4246
2,4,2542.38,1,12,4.36,635.60,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2149
3,5,4416.75,1,12,2.31,883.35,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2585
4,5,2708.92,1,79,0.05,541.78,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2874
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33465,3,3117.15,0,60,17.94,1039.05,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1174
33466,5,3338.02,1,42,2.69,667.60,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2180
33467,5,3592.89,1,0,35.68,718.58,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3659
33468,1,3227.65,1,22,12.13,3227.65,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,583
33469,8,1884.21,0,55,0.09,235.53,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3307

In [55]:
y

0        0
1        0
2        1
3        0
4        0
        ..
33465    0
33466    0
33467    0
33468    0
33469    0
Name: churn, Length: 33470, dtype: int64

In [58]:
## split into train and test sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [59]:
## Apply StandardScaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [60]:
## Define model parameters for hyperparameter tunning
param_grid = {
    'learning_rate':[0.01,0.05,0.11],
    'num_leaves':[20,31,40],
    'max_depth':[1,10,20],
    'min_child_samples':[10,20,30],
    'subsample':[0.7,0.8,0.9],
    'colsample_bytree':[0.7,0.8,0.9]
}

In [63]:
!pip install lightgbm

Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.17.0 in c:\users\hasmit\anaconda3\lib\site-packages (from lightgbm) (1.26.4)
Requirement already satisfied: scipy in c:\users\hasmit\anaconda3\lib\site-packages (from lightgbm) (1.13.1)
Downloading lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.5 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.5 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.5 MB ? eta -:--:--
   -------------- ------------------------- 0.5/1.5 MB 357.1 kB/s eta 0:00:03
   --------------------- ------------------ 0.8/1.5 MB 532.8 kB/s eta 0:00:02
   ---------------------------- ----------- 1.0/1.5 MB 653.7 kB/s eta 0:00:01
   ------------------------------------ --- 1.3/1.5 MB 729.7 kB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 739.2 kB/s eta 0:00:00
Installing collected packages: lightgbm
Successfully installed lightgbm-4.6.0

In [64]:
import lightgbm as lgb
lgb_model=lgb.LGBMClassifier(objective='binary',metric='auc',random_state=42)

In [65]:
## perform Grid Search
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(estimator=lgb_model,param_grid=param_grid,cv=3,scoring='roc_auc',n_jobs=-1)
grid_search.fit(X_train,y_train)

[LightGBM] [Info] Number of positive: 8300, number of negative: 18476
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003425 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1151
[LightGBM] [Info] Number of data points in the train set: 26776, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.309979 -> initscore=-0.800217
[LightGBM] [Info] Start training from score -0.800217

GridSearchCV(cv=3,
             estimator=LGBMClassifier(metric='auc', objective='binary',
                                      random_state=42),
             n_jobs=-1,
             param_grid={'colsample_bytree': [0.7, 0.8, 0.9],
                         'learning_rate': [0.01, 0.05, 0.11],
                         'max_depth': [1, 10, 20],
                         'min_child_samples': [10, 20, 30],
                         'num_leaves': [20, 31, 40],
                         'subsample': [0.7, 0.8, 0.9]},
             scoring='roc_auc')

In [66]:
best_params=grid_search.best_params_
print("Best Parameters found:",best_params)

Best Parameters found: {'colsample_bytree': 0.9, 'learning_rate': 0.11, 'max_depth': 20, 'min_child_samples': 10, 'num_leaves': 40, 'subsample': 0.7}

In [67]:
## Train LightGBM with best parameters
best_model=lgb.LGBMClassifier(**best_params)
best_model.fit(X_train,y_train)

[LightGBM] [Info] Number of positive: 8300, number of negative: 18476
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007483 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1151
[LightGBM] [Info] Number of data points in the train set: 26776, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.309979 -> initscore=-0.800217
[LightGBM] [Info] Start training from score -0.800217

LGBMClassifier(colsample_bytree=0.9, learning_rate=0.11, max_depth=20,
               min_child_samples=10, num_leaves=40, subsample=0.7)

In [68]:
## predict
import numpy as np
import warnings
warnings.simplefilter("ignore")
y_pred_prob = best_model.predict_proba(X_test)[:,1]
y_pred = np.where(y_pred_prob > 0.5, 1,0)

In [69]:
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix, roc_curve

In [70]:
# Evaluation
accuracy = accuracy_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_preb)
print(f'Accuracy: {accuracy:.4f}')
print(f'ROC AUC Score: {roc_auc:.4f}')
print(classification_report(y_test, y_pred))

NameError: name 'y_preb' is not defined